# Generated by Django 3.1 on 2020-08-31 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('province', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=300)),
                ('house_number', models.CharField(max_length=300)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('province', models.CharField(max_length=300)),
                ('district', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('delivery_option', models.CharField(choices=[('Express', 'Express'), ('Regular', 'Regular')], default='Regular', max_length=300)),
                ('status', models.CharField(choices=[('Waiting pickup', 'Waiting pickup'), ('On way', 'On way'), ('Delivered', 'Delivered'), ('Checking', 'Checking')], default='Waiting pickup', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postapp.office')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('receiver_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_address', to='postapp.address')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('sender_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_address', to='postapp.address')),
            ],
        ),
    ]
