# Generated by Django 3.1 on 2020-09-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Express', 'Express')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='receiver_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_address', to='postapp.address'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('On way', 'On way'), ('Waiting pickup', 'Waiting pickup'), ('Checking', 'Checking'), ('Delivered', 'Delivered')], default='Waiting pickup', max_length=300),
        ),
    ]
