# Generated by Django 3.1 on 2020-09-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20200901_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Express', 'Express'), ('Regular', 'Regular')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='picked_up_at_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='postapp.office'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Waiting pickup', 'Waiting pickup'), ('On way', 'On way'), ('Delivered', 'Delivered')], default='Waiting pickup', max_length=300),
        ),
    ]
