# Generated by Django 3.1 on 2020-10-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_auto_20200901_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='image',
            field=models.ImageField(null=True, upload_to='item_images'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Express', 'Express')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Waiting pickup', 'Waiting pickup'), ('Delivered', 'Delivered'), ('On way', 'On way')], default='Waiting pickup', max_length=300),
        ),
    ]
