# Generated by Django 3.1 on 2020-10-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20201017_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='parcel',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Checking', 'Checking'), ('On way', 'On way'), ('Waiting pickup', 'Waiting pickup')], default='Waiting pickup', max_length=300),
        ),
    ]
