# Generated by Django 3.1 on 2020-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0005_auto_20201017_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Waiting pickup', 'Waiting pickup'), ('Checking', 'Checking'), ('Delivered', 'Delivered'), ('On way', 'On way')], default='Waiting pickup', max_length=300),
        ),
    ]
