# Generated by Django 3.1 on 2020-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0006_auto_20201017_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Waiting pickup', 'Waiting pickup'), ('Checking', 'Checking'), ('On way', 'On way')], default='Waiting pickup', max_length=300),
        ),
    ]
