# Generated by Django 3.1 on 2020-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0007_auto_20201203_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Waiting pickup', 'Waiting pickup'), ('Waiting', 'Waiting'), ('Accepted', 'Accepted'), ('On way', 'On way'), ('Checking', 'Checking'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Waiting pickup', max_length=300),
        ),
    ]
