# Generated by Django 3.1 on 2020-12-06 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postapp', '0008_auto_20201203_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=2),
        ),
        migrations.AddField(
            model_name='parcel',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=2),
        ),
        migrations.AddField(
            model_name='parcel',
            name='dimension_width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=2),
        ),
        migrations.AddField(
            model_name='parcel',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picked_up_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Rejected', 'Rejected'), ('On way', 'On way'), ('Waiting pickup', 'Waiting pickup'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('Waiting', 'Waiting')], default='Waiting pickup', max_length=300),
        ),
    ]
