# Generated by Django 3.1 on 2020-12-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0009_auto_20201206_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Express', 'Express'), ('Regular', 'Regular')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='dimension_height',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='dimension_length',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='dimension_width',
            field=models.DecimalField(decimal_places=2, default=0, help_text='in mm', max_digits=10),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Waiting pickup', 'Waiting pickup'), ('On way', 'On way'), ('Rejected', 'Rejected'), ('Checking', 'Checking'), ('Delivered', 'Delivered'), ('Waiting', 'Waiting')], default='Waiting pickup', max_length=300),
        ),
    ]
