# Generated by Django 3.1 on 2020-12-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0010_auto_20201206_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Express', 'Express')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Checking', 'Checking'), ('On way', 'On way'), ('Waiting pickup', 'Waiting pickup'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Waiting pickup', max_length=300),
        ),
    ]
