# Generated by Django 3.1 on 2020-12-14 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0011_auto_20201207_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('Checking', 'Checking'), ('Waiting pickup', 'Waiting pickup'), ('On way', 'On way'), ('Delivered', 'Delivered'), ('Waiting', 'Waiting'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default='Waiting pickup', max_length=300),
        ),
    ]
