# Generated by Django 3.1 on 2020-12-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0012_auto_20201214_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_option',
            field=models.CharField(choices=[('Express', 'Express'), ('Regular', 'Regular')], default='Regular', max_length=300),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('On way', 'On way'), ('Checking', 'Checking'), ('Waiting pickup', 'Waiting pickup'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Waiting', 'Waiting'), ('Delivered', 'Delivered')], default='Waiting pickup', max_length=300),
        ),
    ]
